openapi: 3.0.0
info:
  title: onecx-bookmark-svc
  description: Backend service for bookmarks. You can manage bookmarks for your workspaces here
  version: 1.0.0
  contact:
    email: "tkit_dev@1000kit.org"
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: "http://onecx-bookmark-svc:8080"
tags:
  - name: bookmarksInternal
  - name: staticBookmarksInternal
paths:
  /internal/bookmarks:
    post:
      security:
        - oauth2: [ ocx-bm:all, ocx-bm:write ]
      tags:
        - bookmarksInternal
      description: create bookmark item
      operationId: createNewBookmark
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateBookmark'
      responses:
        '201':
          description: Bookmark created
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetailResponse'
  /internal/bookmarks/search:
    post:
      security:
        - oauth2: [ ocx-bm:all, ocx-bm:read ]
      tags:
        - bookmarksInternal
      description: search bookmarks by criteria
      operationId: searchBookmarksByCriteria
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BookmarkSearchCriteria'
      responses:
        '200':
          description: A list of bookmarks
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BookmarkPageResult'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetailResponse'
  /internal/bookmarks/user:
    post:
      security:
        - oauth2: [ ocx-bm:all, ocx-bm:read ]
      tags:
        - bookmarksInternal
      description: search user bookmarks by criteria
      operationId: searchUserBookmarksByCriteria
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BookmarkSearchCriteria'
      responses:
        '200':
          description: A list of bookmarks
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BookmarkPageResult'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetailResponse'
  /internal/bookmarks/{id}:
    put:
      security:
        - oauth2: [ ocx-bm:all, ocx-bm:write ]
      tags:
        - bookmarksInternal
      description: Update a bookmark's displayName
      operationId: updateBookmark
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateBookmark'
      responses:
        "204":
          description: Bookmark updated
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetailResponse'
        "404":
          description: Bookmark not found
    delete:
      security:
        - oauth2: [ ocx-bm:all, ocx-bm:delete ]
      tags:
        - bookmarksInternal
      description: Delete a bookmark by id
      operationId: deleteBookmarkById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "204":
          description: No Content
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetailResponse'
  /internal/static/bookmarks:
    post:
      security:
        - oauth2: [ ocx-bm:all, ocx-bm:write ]
      tags:
        - staticBookmarksInternal
      description: create static bookmark item
      operationId: createNewStaticBookmark
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateStaticBookmark'
      responses:
        '201':
          description: Bookmark created
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetailResponse'
  /internal/static/bookmarks/search:
    post:
      security:
        - oauth2: [ ocx-bm:all, ocx-bm:read ]
      tags:
        - staticBookmarksInternal
      description: search static bookmarks by criteria
      operationId: searchStaticBookmarksByCriteria
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StaticBookmarkSearchCriteria'
      responses:
        '200':
          description: A list of bookmarks
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StaticBookmarkPageResult'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetailResponse'
  /internal/static/bookmarks/{id}:
    put:
      security:
        - oauth2: [ ocx-bm:all, ocx-bm:write ]
      tags:
        - staticBookmarksInternal
      description: Update a static bookmark
      operationId: updateStaticBookmark
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateStaticBookmark'
      responses:
        "204":
          description: Bookmark updated
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetailResponse'
        "404":
          description: Bookmark not found
    delete:
      security:
        - oauth2: [ ocx-bm:all, ocx-bm:delete ]
      tags:
        - staticBookmarksInternal
      description: Delete a static bookmark by id
      operationId: deleteStaticBookmarkById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "204":
          description: No Content
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetailResponse'
components:
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: https://oauth.simple.api/token
          scopes:
            ocx-bm:all: Grants access to all operations
            ocx-bm:read: Grants read access
            ocx-bm:delete: Grants delete access
            ocx-bm:write: Grants write access
  schemas:
    StaticBookmarkSearchCriteria:
      required:
        - workspaceName
      type: object
      properties:
        workspaceName:
          type: string
        pageNumber:
          format: int32
          description: The number of page.
          default: 0
          type: integer
        pageSize:
          format: int32
          description: The size of page
          default: 100
          maximum: 1000
          type: integer
    StaticBookmark:
      required:
        - id
        - displayName
        - workspaceName
        - position
      type: object
      properties:
        id:
          type: string
        modificationCount:
          format: int32
          type: integer
        creationDate:
          $ref: '#/components/schemas/OffsetDateTime'
        creationUser:
          type: string
        modificationDate:
          $ref: '#/components/schemas/OffsetDateTime'
        modificationUser:
          type: string
        displayName:
          type: string
        url:
          type: string
        workspaceName:
          type: string
        position:
          format: int32
          type: integer
    StaticBookmarkPageResult:
      type: object
      properties:
        totalElements:
          type: integer
          format: int64
          description: The total elements in the resource.
        number:
          type: integer
          format: int32
          default: 0
        size:
          type: integer
          format: int32
          default: 100
          maximum: 1000
        totalPages:
          type: integer
          format: int64
        stream:
          type: array
          items:
            $ref: '#/components/schemas/StaticBookmark'
    CreateStaticBookmark:
      required:
        - displayName
        - workspaceName
        - position
      type: object
      properties:
        displayName:
          type: string
        url:
          type: string
        workspaceName:
          type: string
        position:
          format: int32
          type: integer
    UpdateStaticBookmark:
      required:
        - displayName
        - modificationCount
        - position
      type: object
      properties:
        modificationCount:
          format: int32
          type: integer
        scope:
          $ref: '#/components/schemas/BookmarkScope'
        displayName:
          type: string
        position:
          format: int32
          type: integer
        url:
          type: string
    BookmarkSearchCriteria:
      required:
        - workspaceName
      type: object
      properties:
        workspaceName:
          type: string
        productName:
          type: string
        appId:
          type: string
        pageNumber:
          format: int32
          description: The number of page.
          default: 0
          type: integer
        pageSize:
          format: int32
          description: The size of page
          default: 100
          maximum: 1000
          type: integer
    Bookmark:
      required:
        - id
        - displayName
        - productName
        - appId
        - scope
        - workspaceName
        - position
      type: object
      properties:
        id:
          type: string
        modificationCount:
          format: int32
          type: integer
        creationDate:
          $ref: '#/components/schemas/OffsetDateTime'
        creationUser:
          type: string
        modificationDate:
          $ref: '#/components/schemas/OffsetDateTime'
        modificationUser:
          type: string
        displayName:
          type: string
        endpointName:
          type: string
        endpointParameters:
          type: object
          additionalProperties:
            type: string
        query:
          type: object
          additionalProperties:
            type: string
        hash:
          type: string
        userId:
          type: string
        workspaceName:
          type: string
        productName:
          type: string
        appId:
          type: string
        scope:
          $ref: '#/components/schemas/BookmarkScope'
        position:
          format: int32
          type: integer
    BookmarkPageResult:
      type: object
      properties:
        totalElements:
          type: integer
          format: int64
          description: The total elements in the resource.
        number:
          type: integer
          format: int32
          default: 0
        size:
          type: integer
          format: int32
          default: 100
          maximum: 1000
        totalPages:
          type: integer
          format: int64
        stream:
          type: array
          items:
            $ref: '#/components/schemas/Bookmark'
    CreateBookmark:
      required:
        - displayName
        - workspaceName
        - productName
        - scope
        - position
      type: object
      properties:
        displayName:
          type: string
        endpointName:
          type: string
        endpointParameters:
          type: object
          additionalProperties:
            type: string
        query:
          type: object
          additionalProperties:
            type: string
        hash:
          type: string
        userId:
          type: string
        workspaceName:
          type: string
        productName:
          type: string
        appId:
          type: string
        scope:
          $ref: '#/components/schemas/BookmarkScope'
        position:
          format: int32
          type: integer
    UpdateBookmark:
      required:
        - displayName
        - modificationCount
        - position
      type: object
      properties:
        modificationCount:
          format: int32
          type: integer
        scope:
          $ref: '#/components/schemas/BookmarkScope'
        displayName:
          type: string
        position:
          format: int32
          type: integer
        endpointName:
          type: string
        endpointParameters:
          type: object
          additionalProperties:
            type: string
        query:
          type: object
          additionalProperties:
            type: string
        hash:
          type: string
        userId:
          type: string
    BookmarkScope:
      type: string
      enum:
        - PRIVATE
        - PUBLIC
    ProblemDetailResponse:
      type: object
      properties:
        errorCode:
          type: string
        detail:
          type: string
        params:
          type: array
          items:
            $ref: '#/components/schemas/ProblemDetailParam'
        invalidParams:
          type: array
          items:
            $ref: '#/components/schemas/ProblemDetailInvalidParam'
    ProblemDetailParam:
      type: object
      properties:
        key:
          type: string
        value:
          type: string
    ProblemDetailInvalidParam:
      type: object
      properties:
        name:
          type: string
        message:
          type: string
    OffsetDateTime:
      format: date-time
      type: string
      example: 2022-03-10T12:15:50-04:00
