openapi: 3.0.0
info:
  title: onecx-bookmark internal service
  description: This API provides endpoints to manage Bookmarks
  version: 1.0.0
servers:
  - url: "http://onecx-bookmark-svc:8080"
tags:
  - name: bookmarksInternal
    description: Managing Bookmarks
paths:
  /internal/bookmarks:
    post:
      security:
        - oauth2: [ ocx-bm:all, ocx-bm:write ]
      tags:
        - bookmarksInternal
      description: Create a new bookmark
      operationId: createNewBookmark
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateBookmark'
      responses:
        '201':
          description: Bookmark created successfully
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetailResponse'
  /internal/bookmarks/search:
    post:
      security:
        - oauth2: [ ocx-bm:all, ocx-bm:read ]
      tags:
        - bookmarksInternal
      description: Search bookmarks by search criteria
      operationId: searchBookmarksByCriteria
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BookmarkSearchCriteria'
      responses:
        '200':
          description: Bookmark search results retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BookmarkPageResult'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetailResponse'
  /internal/bookmarks/user:
    post:
      security:
        - oauth2: [ ocx-bm:all, ocx-bm:read ]
      tags:
        - bookmarksInternal
      description: Search bookmarks by criteria for the requesting user
      operationId: searchUserBookmarksByCriteria
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BookmarkSearchCriteria'
      responses:
        '200':
          description: Bookmark search results retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BookmarkPageResult'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetailResponse'
  /internal/bookmarks/{id}:
    put:
      security:
        - oauth2: [ ocx-bm:all, ocx-bm:write ]
      tags:
        - bookmarksInternal
      description: Update a bookmark by its id
      operationId: updateBookmark
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateBookmark'
      responses:
        "204":
          description: Bookmark updated successfully
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetailResponse'
        "404":
          description: Bookmark not found
    delete:
      security:
        - oauth2: [ ocx-bm:all, ocx-bm:delete ]
      tags:
        - bookmarksInternal
      description: Delete a bookmark by its id
      operationId: deleteBookmarkById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "204":
          description: Bookmark deleted successfully
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetailResponse'
components:
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: https://oauth.simple.api/token
          scopes:
            ocx-bm:all: Grants access to all operations
            ocx-bm:read: Grants read access
            ocx-bm:delete: Grants delete access
            ocx-bm:write: Grants write access
  schemas:
    BookmarkSearchCriteria:
      required:
        - workspaceName
      type: object
      properties:
        workspaceName:
          type: string
        productName:
          type: string
        appId:
          type: string
        scope:
          $ref: '#/components/schemas/BookmarkScope'
        pageNumber:
          format: int32
          description: The number of page.
          default: 0
          type: integer
        pageSize:
          format: int32
          description: The size of page
          default: 100
          maximum: 1000
          type: integer
    Bookmark:
      required:
        - id
        - displayName
        - scope
        - workspaceName
        - position
      type: object
      properties:
        id:
          type: string
        modificationCount:
          format: int32
          type: integer
        creationDate:
          $ref: '#/components/schemas/OffsetDateTime'
        creationUser:
          type: string
        modificationDate:
          $ref: '#/components/schemas/OffsetDateTime'
        modificationUser:
          type: string
        displayName:
          type: string
        endpointName:
          type: string
        endpointParameters:
          type: object
          additionalProperties:
            type: string
        query:
          type: object
          additionalProperties:
            type: string
        fragment:
          type: string
        url:
          type: string
        userId:
          type: string
        workspaceName:
          type: string
        productName:
          type: string
        appId:
          type: string
        scope:
          $ref: '#/components/schemas/BookmarkScope'
        position:
          format: int32
          type: integer
        imageUrl:
          type: string
        external:
          type: boolean
        target:
          $ref: '#/components/schemas/Target'
        disabled:
          type: boolean
          default: false
    BookmarkPageResult:
      type: object
      properties:
        totalElements:
          type: integer
          format: int64
          description: The total elements in the resource.
        number:
          type: integer
          format: int32
          default: 0
        size:
          type: integer
          format: int32
          default: 100
          maximum: 1000
        totalPages:
          type: integer
          format: int64
        stream:
          type: array
          items:
            $ref: '#/components/schemas/Bookmark'
    CreateBookmark:
      required:
        - displayName
        - workspaceName
        - scope
        - position
      type: object
      properties:
        displayName:
          type: string
        endpointName:
          type: string
        endpointParameters:
          type: object
          additionalProperties:
            type: string
        query:
          type: object
          additionalProperties:
            type: string
        fragment:
          type: string
        url:
          type: string
        userId:
          type: string
        workspaceName:
          type: string
        productName:
          type: string
        appId:
          type: string
        scope:
          $ref: '#/components/schemas/BookmarkScope'
        position:
          format: int32
          type: integer
        imageUrl:
          type: string
        external:
          type: boolean
        target:
          $ref: '#/components/schemas/Target'
        disabled:
          type: boolean
          default: false
    UpdateBookmark:
      required:
        - displayName
        - modificationCount
        - position
      type: object
      properties:
        modificationCount:
          format: int32
          type: integer
        scope:
          $ref: '#/components/schemas/BookmarkScope'
        displayName:
          type: string
        position:
          format: int32
          type: integer
        endpointName:
          type: string
        endpointParameters:
          type: object
          additionalProperties:
            type: string
        query:
          type: object
          additionalProperties:
            type: string
        fragment:
          type: string
        url:
          type: string
        userId:
          type: string
        imageUrl:
          type: string
        external:
          type: boolean
        target:
          $ref: '#/components/schemas/Target'
        disabled:
          type: boolean
          default: false
    BookmarkScope:
      type: string
      enum:
        - PRIVATE
        - PUBLIC
    Target:
      type: string
      enum:
        - _self
        - _blank
    ProblemDetailResponse:
      type: object
      properties:
        errorCode:
          type: string
        detail:
          type: string
        params:
          type: array
          items:
            $ref: '#/components/schemas/ProblemDetailParam'
        invalidParams:
          type: array
          items:
            $ref: '#/components/schemas/ProblemDetailInvalidParam'
    ProblemDetailParam:
      type: object
      properties:
        key:
          type: string
        value:
          type: string
    ProblemDetailInvalidParam:
      type: object
      properties:
        name:
          type: string
        message:
          type: string
    OffsetDateTime:
      format: date-time
      type: string
      example: 2022-03-10T12:15:50-04:00
